name: Build and Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Update version
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b temp-branch
        sed -i "s/__version__ = \"0.0.0\"/__version__ = \"${{ github.ref_name }}\"/" dabbler/__init__.py
        git add dabbler/__init__.py
        git commit -m "Bump version to ${{ github.ref_name }}"
        git push origin HEAD:main

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1